name: Release Enjoy App
on: workflow_dispatch

permissions:
  contents: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15
            arch: arm64
          - os: macos-13
            arch: x64
          - os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Install Apple certificate
        if: contains(matrix.os, 'macos')
        env:
          MACOS_CERTIFICATE_APPLICATION_BASE64: ${{ secrets.MACOS_CERTIFICATE_APPLICATION_BASE64 }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: ./enjoy/scripts/add-macos-cert.sh

      - name: Build installers
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          npm_config_arch: ${{ matrix.arch }}
          PACKAGE_OS_ARCH: ${{ matrix.arch }}
        run: |
          cd enjoy
          yarn run cross-env NODE_OPTIONS='--max-old-space-size=8192' rimraf .vite
          yarn run download
          yarn run electron-forge make --arch=${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Enjoy-${{ runner.os }}-${{ matrix.arch }}-build-${{ github.ref_name }}
          path: |
            enjoy/out/make/**/*.exe
            enjoy/out/make/**/*.dmg

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            enjoy/out/make/**/*.exe
            enjoy/out/make/**/*.dmg
          tag_name: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
